name: 3. Lang And Zs To Paratranz

on:
  issues:
    types: [opened]

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}

  VALID_LABEL: 自动化:lang+zs→paratranz
  VALID_USER: ${{ github.repository_owner }}

  MODPACK_PATH: .modpack.local.d

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, '自动化:lang+zs→paratranz')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        id: check-and-parse-issue
        uses: Kiwi233/Translation-of-GTNH/.github/actions/run-script@master
        with:
          script: parse-issue.ts
          args: lang-and-zs-to-paratranz
        env:
          GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
          VALID_LABEL: ${{ env.VALID_LABEL }}
          VALID_USER: ${{ env.VALID_USER }}
    outputs:
      passed: ${{ steps.check-and-parse-issue.outputs.passed }}
      modpack-url: ${{ steps.check-and-parse-issue.outputs.modpack-url }}

  close-issue:
    name: Close Issue
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            此模板仅由内部人员使用，已自动关闭。

  lang-and-zs-to-paratranz:
    name: Lang And Zs To Paratranz
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Compare Repo
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-compare-repo@master

      - name: Setup Bun
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-bun@master

      - name: Ensure Modpack
        uses: Kiwi233/Translation-of-GTNH/.github/actions/ensure-modpack@master
        with:
          url: ${{ needs.check-and-parse-issue.outputs.modpack-url }}
          root: ${{ env.MODPACK_PATH }}

      - name: Run Script
        run: >-
          bun run src/index.ts to-paratranz:lang-zs
          --modpack-path='${{ env.MODPACK_PATH }}'

      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            已自动同步至 Paratranz。
