name: 3. Gt Lang To Paratranz

on:
  issues:
    types: [opened]

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}

  VALID_LABEL: 自动化:gt-lang→paratranz
  VALID_USER: ${{ github.repository_owner }}

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, '自动化:gt-lang→paratranz')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/scripts

      - name: Setup Bun
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-bun@master

      - name: Run Script
        id: check-and-parse-issue
        env:
          GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
          VALID_LABEL: ${{ env.VALID_LABEL }}
          VALID_USER: ${{ env.VALID_USER }}
        run: |
          bun run -i .github/scripts/parse-issue.ts gt-lang-to-paratranz
    outputs:
      passed: ${{ steps.check-and-parse-issue.outputs.passed }}
      gt-lang-url: ${{ steps.check-and-parse-issue.outputs.gt-lang-url }}

  close-issue:
    name: Close Issue
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            此模板仅由内部人员使用，已自动关闭。

  gt-lang-to-paratranz:
    name: Gt Lang To Paratranz
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Compare Repo
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-compare-repo@master

      - name: Setup Bun
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-bun@master

      - name: Run Script
        run: >-
          bun run src/index.ts to-paratranz:gt-lang
          --gt-lang-url='${{ needs.check-and-parse-issue.outputs.gt-lang-url }}'

      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            已自动同步至 Paratranz。
