name: Compare Quest Book

on:
  issues:
    types: [ opened ]

jobs:
  check-and-parse-issue:
    if: contains(github.event.issue.labels.*.name, '自动化:questbook')
    name: Check And Parse Issue
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Checkout MuXiu1997/GTNH-translation-compare
        uses: actions/checkout@v3
        with:
          repository: MuXiu1997/GTNH-translation-compare
      - name: Run Script
        id: check-and-parse-issue
        env:
          GITHUB_ISSUE: ${{ toJSON(github.event.issue) }}
          VALID_LABEL: 自动化:questbook
          VALID_USER: ${{ github.repository_owner }}
        run: |
          python3 parse_issue_compare_quest_book.py
    outputs:
      passed: ${{ steps.check-and-parse-issue.outputs.passed }}
      branch: ${{ steps.check-and-parse-issue.outputs.branch }}

  close-issue:
    name: Close Issue
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2.0.0
        with:
          comment: |
            此模板仅由内部人员使用，已自动关闭。

  compare:
    name: Compare
    needs: check-and-parse-issue
    if: ${{ needs.check-and-parse-issue.outputs.passed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Checkout MuXiu1997/GTNH-translation-compare
        uses: actions/checkout@v3
        with:
          repository: MuXiu1997/GTNH-translation-compare
      - name: Checkout Work Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check-and-parse-issue.outputs.branch }}
          path: '.repo'
      - name: Setup Git
        run: |
          git config user.name 'MuXiu1997'
          git config user.email 'muxiu1997@gmail.com'
        working-directory: '.repo'
      - name: Compare
        id: compare
        run: >-
          python3 compare_quest_book.py
          --repo-path='.repo'
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.0.0
        with:
          title: '[自动化]生成任务书lang文件'
          body: |
            - Closes #${{ github.event.issue.number }}
          labels: |
            自动化:questbook
          branch: automation/compare/${{ github.event.issue.number }}
          path: '.repo'
          delete-branch: true
